name: notebook

services:
  postgres:
    image: postgres
    container_name: notebook-postgres
    environment:
      POSTGRES_DB: notebook
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - notebook_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  notebook_postgres_data:

#  environment:
#       - POSTGRES_DB=${DB_NAME:-proapay_dev}
#       - POSTGRES_USER=${DB_USER:-postgres}
#       - POSTGRES_PASSWORD=${DB_PASSWORD:-password}
#     ports:
#       - ${DB_PORT:-54322}:5432
